name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch ${{ github.repository }}"
  analysis:
    uses: ./.github/workflows/analysis.yml

#  test:
#    needs: [ analysis ]
#    uses: 5peak2me/github-actions-workflow-android/.github/workflows/test.yml@main
#
#  build:
#    needs: [ analysis, test ]
#    uses: 5peak2me/github-actions-workflow-android/.github/workflows/build.yml@main
