name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch ${{ github.repository }}"
  analysis:
    uses: ./.github/workflows/analysis.yml

  test:
    needs: [ analysis ]
    uses: ./.github/workflows/test.yml

  build:
    needs: [ analysis, test ]
    uses: ./.github/workflows/build.yml
